version: '3.8'

services:
  mcp-memory:
    build: .
    container_name: mcp-memory-server
    restart: unless-stopped
    
    ports:
      - "8081:8081"
    
    volumes:
      - memory_data:/app/data
    
    environment:
      - PORT=8081
      - MEMORY_FILE_PATH=/app/data/memory.json
    
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --spider http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  memory_data:
